### ISSUE TITLE
Fonts at bottom of page don't look right

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2020#11]
for example of https://open-security-summit.org/participant/ page

![image](https://user-images.githubusercontent.com/656739/75120144-0271be00-5681-11ea-81b9-0df86cddceef.png)

**Comment by fzipi** [comment]
@DinisCruz Do you have an example of the font you need there? It is the same as 2019.....

**Comment by DinisCruz** [comment]
this is done
