### ISSUE TITLE
Lightning talk link has stopped working

### ISSUE THREAD

**Issue by IanTaylorFB** [OpenSecuritySummit/oss2020#647]
Thanks for merging PR #645.
However the link from the lightning talk [The Future of CNI](https://open-security-summit.org/tracks/lightning-talk/the-future-of-cni/) to Jacqui Taylor's speaker page [Dr Jacqui Taylor](https://open-security-summit.org/participant/organizers/jacqui-taylor/) has stopped working.

Note that we changed the `title` attribute in `jacqui-taylor.md` to `Dr Jacqui Taylor` - did this break the link?

Please advise what I need to change to make the link work and I'll make another PR.

TIA

**Comment by olegtaranenko** [comment]
@IanTaylorFB I fixed the issue. Really to keep link to the Jacqui need to change Name in both  participant & session descriptions
